# Generated by Django 5.0.6 on 2024-12-13 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('checkout_id', models.CharField(max_length=150)),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de pagamento')),
                ('is_installment', models.BooleanField(blank=True, default=False, verbose_name='Está parcelado?')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('order_number', models.CharField(default='', max_length=20, verbose_name='Numero do Pedido')),
                ('order_status', models.CharField(choices=[('PEN', 'Pendente'), ('CAN', 'Cancelado'), ('ENT', 'Entregue')], default='PEN', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitaty', models.IntegerField(verbose_name='Quantidade')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.color', verbose_name='Cor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.glasses', verbose_name='Produto')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.paymentorder', verbose_name='Pedido')),
            ],
        ),
    ]
