# Generated by Django 5.0.6 on 2024-12-09 02:51

import data.models.glasses
import data.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('css_color', models.CharField(blank=True, help_text='Esse campo será usado para identificar a cor', max_length=40, verbose_name='Valor RGB')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
            },
        ),
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Data da ultima edição')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('material', models.CharField(max_length=50, verbose_name='Material do Óculos')),
                ('quantitaty', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('installments_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de parcelamento')),
                ('installments_count', models.IntegerField(verbose_name='Quantidade de parcelas')),
                ('discount', models.IntegerField(default=0, validators=[data.utils.validators.min_and_max_discount_value_validator], verbose_name='Desconto (Porcentagem)')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('U', 'Unissex')], max_length=20, verbose_name='Gênero')),
                ('is_sample', models.BooleanField(blank=True, default=False, help_text='Indica que o produto estará na pagina principal como recomendação.', verbose_name='Listar no inicio da página?')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Está em promoção?')),
                ('slug', models.SlugField(help_text='Este campo é gerado automaticamente. É usado para identificação nos campos de buscas e filtragem. Deve ser único.', max_length=240, unique=True)),
                ('bridge', models.CharField(max_length=30, verbose_name='Ponte')),
                ('nose_pads', models.CharField(max_length=50, verbose_name='Protetor de nariz')),
                ('temple', models.CharField(max_length=30, verbose_name='Hastes')),
                ('rim', models.CharField(max_length=30, verbose_name='Aro')),
                ('description', models.TextField(max_length=800, verbose_name='Descrição')),
                ('width', models.CharField(max_length=30, verbose_name='Largura')),
                ('height', models.CharField(max_length=30, verbose_name='Altura')),
                ('warranty', models.CharField(max_length=20, verbose_name='Tempo de garantia')),
                ('brand', models.ManyToManyField(related_name='glasses_brand', to='data.brand', verbose_name='Marca')),
                ('category', models.ManyToManyField(related_name='glasses_category', to='data.category', verbose_name='Categorias')),
                ('color', models.ManyToManyField(related_name='glasses_color', to='data.color', verbose_name='Cor')),
                ('model', models.ManyToManyField(related_name='glasses_model', to='data.model', verbose_name='Modelo')),
                ('shape', models.ManyToManyField(related_name='glasses_shape', to='data.shape', verbose_name='Formato')),
            ],
            options={
                'verbose_name': 'Óculos',
                'verbose_name_plural': 'Óculos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, max_length=150, upload_to=data.models.glasses.Image.create_image_path, verbose_name='Imagem')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(help_text='Ordem de exibição das imagens', verbose_name='Ordem de exibição')),
                ('glasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.glasses', verbose_name='Oculos')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['glasses'],
            },
        ),
    ]
