# Generated by Django 5.0.6 on 2024-12-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='API Name')),
                ('url', models.CharField(max_length=150, verbose_name='Endereço da API')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='API Reference')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_domain', models.CharField(blank=True, max_length=100, verbose_name='Dominio do site externo')),
                ('site_name', models.CharField(max_length=100, verbose_name='Nome do site')),
                ('site_domain', models.CharField(max_length=100, verbose_name='Dominio')),
                ('max_image_size', models.IntegerField(default=2, verbose_name='Tamanho maximo de arquivos (MB)')),
                ('max_file_per_comment', models.IntegerField(default=3, verbose_name='Tamanho maximo de arquivos permitido por comentário')),
                ('max_product_pagination', models.IntegerField(default=15, verbose_name='Tamanho maximo de produtos por pesquisa (Paginação)')),
                ('max_comments_pagination', models.IntegerField(default=5, verbose_name='Tamanho maximo de comentários (Paginação)')),
                ('max_product_query_pagination', models.IntegerField(default=5, verbose_name='Tamanho maximo maximo de produtos por pesquisa dinamica (Paginação)')),
                ('default_image_url', models.CharField(max_length=150, verbose_name='Imagem padrão para quando produto não possui imagem')),
                ('filter_1', models.CharField(blank=True, max_length=30, verbose_name='Nome de filtro 1')),
                ('param_1', models.CharField(blank=True, max_length=30, verbose_name='Parametro de pesquisa 1')),
                ('filter_2', models.CharField(blank=True, max_length=30, verbose_name='Nome de filtro 2')),
                ('param_2', models.CharField(blank=True, max_length=30, verbose_name='Parametro de pesquisa 2')),
                ('filter_3', models.CharField(blank=True, max_length=30, verbose_name='Nome de filtro 3')),
                ('param_3', models.CharField(blank=True, max_length=30, verbose_name='Parametro de pesquisa 3')),
                ('filter_4', models.CharField(blank=True, max_length=30, verbose_name='Nome de filtro 4')),
                ('param_4', models.CharField(blank=True, max_length=30, verbose_name='Parametro de pesquisa 4')),
                ('filter_5', models.CharField(blank=True, max_length=30, verbose_name='Nome de filtro 5')),
                ('param_5', models.CharField(blank=True, max_length=30, verbose_name='Parametro de pesquisa 5')),
                ('filter_6', models.CharField(blank=True, max_length=30, verbose_name='Nome de filtro 6')),
                ('param_6', models.CharField(blank=True, max_length=30, verbose_name='Parametro de pesquisa 6')),
            ],
        ),
    ]
